### ISSUE TITLE
Configuration error in v2.1.0

### ISSUE THREAD

**Issue by bragig** [WSCF/WSCF#3]
Hi,
Thanks for the great work on the migration to Visual Studio Extension.

We're trying out v2.1.0 and we're getting the following error when using "Generate Web Service Code..." this error does not appear in v1.0.14 (using Add-In). 

![image](https://user-images.githubusercontent.com/1774143/30908989-0d7dd67a-a36f-11e7-9316-79a16514755a.png)

Here is the config dialog:
![image](https://user-images.githubusercontent.com/1774143/30909132-960e870a-a36f-11e7-971f-c83a1d5441c7.png)

Regards,
Bragi

**Comment by mbarqawi** [comment]
I have the same issue I think it related to WSDL , try to remove it and it will work

**Comment by bragig** [comment]
Works if i uncheck "Enable WSDL Endpoint", so that's a workaround.

Thanks @mbarqawi.
