### ISSUE TITLE
Visual Studio marketplace

### ISSUE THREAD

**Issue by jawn** [WSCF/WSCF#7]
Is this extension available in the Visual Studio marketplace?

**Comment by ChristianWeyer** [comment]
Hi!

this project is really in kind of a stalled mode for a long time.
If you want to pro-actively work on it, let us know!

**Comment by jawn** [comment]
Hi Christian,

It's not a priority for me to have it in the marketplace, just curious to know whether it's there :)

I suppose this means it's not and the place to get it is the release page in this repo.

**Comment by ChristianWeyer** [comment]
Exactly.
However, the offer still stands: you can get a contributor, if you like.

**Comment by jawn** [comment]
That's a very kind offer. However, I will reject it.
